# Generated by Django 4.0.4 on 2022-05-06 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_pizza_name_rename_topic_pizza_delete_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='pizza_name',
            name='date_added',
        ),
        migrations.CreateModel(
            name='toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.TextField(verbose_name='pizza')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.pizza_name')),
            ],
        ),
    ]
