# Generated by Django 4.0.4 on 2022-05-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_remove_pizza_date_added_remove_pizza_name_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.TextField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.pizza'))),
            ],
            options={
                'verbose_name_plural': 'toppings',
            },
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='topping',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='text',
            field=models.TextField(verbose_name='pizza_name'),
        ),
        migrations.DeleteModel(
            name='pizza_name',
        ),
        migrations.DeleteModel(
            name='toppings',
        ),
        migrations.AddField(
            model_name='topping',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.pizza'),
        ),
    ]
