# Generated by Django 4.0.4 on 2022-05-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0004_topping_remove_toppings_topping_alter_pizza_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='topping_name',
            field=models.TextField(),
        ),
    ]
