# Generated by Django 3.2.13 on 2022-05-07 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0005_alter_topping_topping_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='text',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topping',
            name='topping_name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.pizza')),
            ],
        ),
    ]
